# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_auto_20170804_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolsscript',
            old_name='create_time',
            new_name='ctime',
        ),
    ]
