# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0003_auto_20170804_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsscript',
            name='tool_run_type',
            field=models.CharField(max_length=255, verbose_name='脚本类型'),
        ),
    ]
