# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0002_auto_20170802_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cpu_use',
        ),
        migrations.RemoveField(
            model_name='host',
            name='mem_use',
        ),
    ]
