# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0004_toolsscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsscript',
            name='tool_run_type',
            field=models.IntegerField(choices=[(0, 'Shell'), (1, 'Python')], default=0, verbose_name='脚本类型'),
        ),
    ]
