# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0005_auto_20170804_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolsScript',
        ),
    ]
